PROJECT_NAME: "AWS Deployment Test Project"
API_PREFIX: "/api/test"
MODEL:
    PATH: "ml_models/catvdog.pth"
    # DEVICE: "cpu" | "cuda:0" | "cuda:1" | ...
    DEVICE: "cpu"
DB:
    DATABASE: $DATABASE
    USER: $DATABASE_USER
    PASSWORD: $DATABASE_PASSWORD
    HOST: $DATABASE_HOST
    PORT: 5432
AWS:
    ID: $AWS_KEY
    SECRET: $AWS_SECRET
S3_BUCKET: $S3_BUCKET
