PROJECT_NAME: "AWS Deployment Test Project"
API_PREFIX: "/api/test"
MODEL:
    PATH: "ml_models/catvdog.pth"
    # DEVICE: "cpu" | "cuda:0" | "cuda:1" | ...
    DEVICE: "cpu"
DB:
    DATABASE: "predictions"
    USER: "postgres"
    PASSWORD: "postgres"
    HOST: "db"
    PORT: "5432"
