#!/bin/bash
mkdir -p /var/log/gunicorn

cd /deploy || exit 2
poetry install

AWS_DEFAULT_REGION="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)"
export AWS_DEFAULT_REGION
