#!/bin/bash
cd /deploy || exit 2

AWS_DEFAULT_REGION="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)"
export AWS_DEFAULT_REGION

poetry run gunicorn --config infrastructure/aws/codedeploy/gunicorn.ec2.conf app.main:app