version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=predictions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
  api:
    build:
      context: ../..
      dockerfile: infrastructure/local/Dockerfile
    image: fastapi-pytorch
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_KEY=$AWS_KEY
      - AWS_SECRET=$AWS_SECRET
      - S3_BUCKET=$S3_BUCKET
      - DATABASE=$DATABASE
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST


